 
    CREATE TABLE api_publica (
        api_active boolean,
        api_id bigint GENERATED BY DEFAULT AS IDENTITY,
        api_url varchar(2048),
        api_frequencia varchar(255) NOT NULL,
        api_nome varchar(255) NOT NULL,
        descricao TEXT,
        PRIMARY KEY (api_id)
    )
 
    CREATE TABLE noticia (
        por_id integer,
        rep_id integer,
        noti_data timestamp(6),
        noti_id bigint GENERATED BY DEFAULT AS IDENTITY,
        noti_url varchar(2048),
        noti_text varchar(255),
        PRIMARY KEY (noti_id)
    )
 
    CREATE TABLE portal (
        por_data timestamp(6),
        por_id bigint GENERATED BY DEFAULT AS IDENTITY,
        por_frequencia varchar(30),
        por_nome varchar(30),
        por_url varchar(2048),
        PRIMARY KEY (por_id)
    )
 
    CREATE TABLE regionalismo (
        tag_id integer,
        reg_id bigint GENERATED BY DEFAULT AS IDENTITY,
        nome varchar(100),
        PRIMARY KEY (reg_id)
    )
 
    CREATE TABLE reporter (
        por_id bigint,
        rep_id bigint GENERATED BY DEFAULT AS IDENTITY,
        rep_nome varchar(255) NOT NULL,
        PRIMARY KEY (rep_id)
    )
 
    CREATE TABLE result_api (
        api_id bigint,
        res_data timestamp(6),
        res_id bigint GENERATED BY DEFAULT AS IDENTITY,
        res_payload jsonb,
        PRIMARY KEY (res_id)
    )
 
    CREATE TABLE result_tag (
        res_id bigint NOT NULL,
        tag_id bigint NOT NULL,
        PRIMARY KEY (res_id, tag_id)
    )
 
    CREATE TABLE tag (
        tag_active boolean,
        tag_data timestamp(6),
        tag_id bigint GENERATED BY DEFAULT AS IDENTITY,
        tag_nome varchar(30) NOT NULL,
        tag_descricao varchar(250),
        PRIMARY KEY (tag_id)
    )
 
    CREATE TABLE tag_noticia (
        noti_id bigint NOT NULL,
        tag_id bigint NOT NULL,
        PRIMARY KEY (noti_id, tag_id)
    )
 
    CREATE TABLE tag_portal (
        por_id bigint NOT NULL,
        tag_id bigint NOT NULL,
        PRIMARY KEY (por_id, tag_id)
    )
