
services:
  dev-env:
    env_file:
      - path: ./dev.env
    build:
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
        JAVA_VERSION: ${JAVA_VERSION}
        NODE_VERSION: ${NODE_VERSION}

    restart: always
    volumes:
      - ../:/home/ubuntu/app
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.gitconfig:/home/ubuntu/.gitconfig

    tty: true
    user: 1000:1000
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
      - 127.0.0.1:5173:5173
      - 127.0.0.1:5433:5432
